GET http://localhost:3030/getAuthor?page=1
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJldWdlbmlvMTAiLCJsYXN0TmFtZSI6InBhdm9uMTAiLCJlbWFpbCI6ImNhbmUuZ2F0dG9AZ21haWwuaXQiLCJpYXQiOjE3MTIyNDQ1MTQsImV4cCI6MTcxMjMzMDkxNH0.7PkiPsq3xml2Vt2DrmSlfnMCyZCFFm_tPA6TUsu6zZg"
####
POST http://localhost:3030/createAuthors
Content-Type: application/json
    
    {
    "firstName":"eugenio11",
    "lastName":"pavon11",
    "email":"cane.gatto2@gmail.it",
    "password":"abcdef12",
    "dateOfBirth":"12342",
    "avatar":"1232"
}
####
GET http://localhost:3030/getAuthor/65f5d8465c4fda7b5ade9ffc
####
PATCH  http://localhost:3030/updateAuthor/65f5d8465c4fda7b5ade9ffc
Content-Type: application/json
    
    {
    
    "email":"abc2@gmail.it"
    
}
####
DELETE http://localhost:3030/deleteAuthor/65f5d84d5c4fda7b5ade9ffe
####

//blogPost

GET http://localhost:3030/blogPosts

Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJldWdlbmlvMTEiLCJsYXN0TmFtZSI6InBhdm9uMTEiLCJlbWFpbCI6ImNhbmUuZ2F0dG8yQGdtYWlsLml0IiwiaWF0IjoxNzEyMjUyNTA3LCJleHAiOjE3MTIzMzg5MDd9.v_xF6XtrlpBrheqpoWaq1BwKO4r3y0EqIkr9yDI5JA4

####
POST http://localhost:3030/blogPosts
Content-Type: application/json
    
    {
    "category":"xyz7",
    "title":"xyz23",
    "cover":"xyz7",
    "readTime":{
       "value": 123,
       "unit":"xyz"

    },
    "author":{
       "name": "xyz",
       "avatar":"xyz"

    },
    "content":"xyz",
    "comments":[]
}

####
POST    http://localhost:3030/blogPosts
Content-Type: application/json
    
    {
    "category":"xyz",
    "title":"xyz3",
    "cover":"xyz",
    "readTime":{
       "value": 123,
       "unit":"xyz"

    },
    "author":{
       "name": "xyz",
       "avatar":"xyz"

    },
    "content":"xyz",
    "comments":[
        {
        "title":"xyz2",
        "body":"xyz"
        
        
    },
    {
        "title":"xyz2",
        "body":"xyz"
        
        
    }
    ]
        
    
}

####
POST    http://localhost:3030/blogPosts/660426b23d504c2de41e7748/comments
Content-Type: application/json
    
    {
    "text":"nice2"
    
}

####
GET    http://localhost:3030/blogPosts/660426b23d504c2de41e7748/comments
Content-Type: application/json
    

####
# PATCH  http://localhost:3030/blogPosts/
# Content-Type: application/json

#     {
#     "comments":[
#         {
#         "title":"xyz2",
#         "body":"xyz"
        
        
#     },
#     {
#         "title":"xyz2",
#         "body":"xyz"
        
        
#     }
#     ]
# }

####
GET http://localhost:3030/blogPosts/660426b23d504c2de41e7748
####
PATCH  http://localhost:3030/blogPosts/65f5d1a3163aa0b50f9b95cc
Content-Type: application/json
    
    {
    
    "category":"uvw"
    
}
####
DELETE http://localhost:3030/blogPosts/65f5d4a32059d6b467ead7f9
####
GET http://localhost:3030/exercise

####
GET http://localhost:3030/exercise/isActive
####
GET http://localhost:3030/exercise/26
####
GET http://localhost:3030/exercise/26e30
####
GET http://localhost:3030/exercise/brown_blue
####
GET http://localhost:3030/exercise/green
####
GET http://localhost:3030/exercise/noGreen_noBlue
####
GET http://localhost:3030/exercise/company
####
# POST http://localhost:3030/getAuthor/cloudUploadImg
# Content-Type: application/json
    
#     {
#     "img":"https://www.zooplus.it/magazine/wp-content/uploads/2020/10/1-37-768x512.jpg"
# }

####
PATCH  http://localhost:3030/updateAuthor/65f5d8465c4fda7b5ade9ffc
Content-Type: application/json
    
    {
    
    "avatar":"http://localhost:3030/uploads/uploadImg-1711460864932-768698325.png"
    
}
####
PATCH  http://localhost:3030/blogPosts/660426b23d504c2de41e7748
Content-Type: application/json
    
    {
    
    "cover":"https://res.cloudinary.com/dhijdwjv7/image/upload/v1711395063/PT043/uwbqhwnh7hf8hpqxuyhj.png"
    
}
####
GET http://localhost:3030/blogPosts/660426b23d504c2de41e7748/comments/660427533d504c2de41e775a

####
POST  http://localhost:3030/blogPosts/660426b23d504c2de41e7748/comments
Content-Type: application/json

{
    "text":"ciao"
}
####
PATCH   http://localhost:3030/blogPosts/660426b23d504c2de41e7748/comments/660427533d504c2de41e775a
Content-Type: application/json

{
    "text":"ciao2"
}
####
DELETE  http://localhost:3030/blogPosts/660426b23d504c2de41e7748/comments/660426b23d504c2de41e774a
####
POST http://localhost:3030/login
Content-Type: application/json

{
    "email":"cane.gatto2@gmail.it",
    "password":"abcdef12"

}
####
